### ISSUE TITLE
support more debian versions

### ISSUE THREAD

**Issue by mcandre** [mcandre/docker-debian#1]
* [x] sid
* [x] 9 stretch
* [x] 8 jessie
* [x] 7 wheezy
* [x] 6 6.0 squeeze
* [x] 5 5.0 lenny
* [x] 4 4.0 etch
* [x] 3.1 sarge
* [x] 3.0 woody
* [x] 2.2 potato
* [x] 2.1 slink
* [x] 2.0 hamm
* [x] 1.3.1 bo
* [ ] 1.2 rex
* [ ] 1.1 buzz

**Comment by mcandre** [comment]
Closing for now. If bootable rex and buzz ISOs are found/generated, and qemu can be setup as a better entrypoint, dockerizing 2.0 hamm, 1.3.1 bo, 1.2 rex, and 1.1 buzz can continue.

**Comment by soobidou** [comment]
Sorry to reply to old post, but I'm searching for OLD debian distros and wonder what's going on with this interesting project ?

I don't see any old debian in mcandre/docker-debien published on Dockerhub. 

The oldest available, AFAIK, is debian/eol:slink
Those old distros are super useful to compile old GCC code (for instance I managed to run old MUD source codes with SLINK.. without it one need to run VMs.. docker is so much more useful for portabilizing such old artifacts)
Cheers,

**Comment by mcandre** [comment]
Per the README, this project is now deprecated.

As mentioned in this issue, it is difficult to locate install media for such old editions.

You may fork this project and continue experimenting.
